### ISSUE TITLE
ValidatableEntryControl cannot "see" IsPassword from Entry

### ISSUE THREAD

**Issue by john-dalsgaard** [james-russo/XamarinForms-UnobtrusiveValidationPlugin#12]
Seems to be in both Xaml and code behind.

**Comment by james-russo** [comment]
@john-dalsgaard 

If you're in a pinch, you can set "IsPassword" from code behind by the following:
`entry.Control.IsPassword = true;` the trick there being "Control". 

I'm working on an update for the Xaml approach since there doesn't seem to be a clean way to set the value from there.  I'll update this ticket with the version number in NuGet with the update.

**Comment by james-russo** [comment]
ValidatableEntryControl updated in version 3.0.64.  NuGet package is now indexed and available.
